name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm audit
      - run: npm run prettier-check
      - run: npm test -- --single-run=true --browsers=ChromeHeadless
        env:
          CI: true
